# Realistic Lite Shaderpack settings

profile.LOW=RLS_REALISM:0.92 RLS_WATER_DETAIL:0.45 RLS_FOG_STRENGTH:0.80 RLS_EXPOSURE:0.78 RLS_SATURATION:1.00 shadowMapResolution:1024 shadowDistance:64.0
profile.BALANCED=RLS_REALISM:1.00 RLS_WATER_DETAIL:0.62 RLS_FOG_STRENGTH:0.66 RLS_EXPOSURE:0.86 RLS_SATURATION:1.02 shadowMapResolution:1024 shadowDistance:72.0
profile.QUALITY=RLS_REALISM:1.08 RLS_WATER_DETAIL:0.80 RLS_FOG_STRENGTH:0.55 RLS_EXPOSURE:0.94 RLS_SATURATION:1.08 shadowMapResolution:1536 shadowDistance:96.0

screen=<profile> RLS_REALISM RLS_EXPOSURE RLS_SATURATION RLS_FOG_STRENGTH RLS_WATER_DETAIL
sliders=RLS_REALISM RLS_EXPOSURE RLS_SATURATION RLS_FOG_STRENGTH RLS_WATER_DETAIL

oldLighting=false
clouds=off
dynamicHandLight=true
underwaterOverlay=false
vignette=false
sun=true
moon=true
stars=true

shadowMapResolution=1024
shadowDistance=64.0
shadowIntervalSize=2.0
generateShadowMipmap=false
generateShadowColorMipmap=false
shadowHardwareFiltering=true

texture.composite.gcolor=gcolor
texture.composite.depthtex0=depthtex0
